### ISSUE TITLE
404 Not Found GET https://registry.npmjs.org/contentful-schema-blog

### ISSUE THREAD

**Issue by stylechains** [ElegantStack/contentful-schema-blog#2]
Hi, There Not Able to Install Contentful Package.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/contentful-schema-blog - Not found
npm ERR! 404 
npm ERR! 404  'contentful-schema-blog@1.0.0' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
Also check scrn-shot
https://prnt.sc/1l0aMGYkaKXl

**Comment by ElegantStack** [comment]
Please submit a support ticket from ThemeForest.
